#Multiple Linear Regression

##Importing the Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



##Importing the DataSet

In [2]:
database = pd.read_csv('DummyData.csv')
X = database.iloc[ : , :-1].values
Y = database.iloc[ : , -1].values

In [3]:
print(X)

[[4.70e+02 6.00e-01 1.09e-01 2.25e+00]
 [4.70e+02 5.00e-01 1.39e-01 2.33e+00]
 [4.70e+02 6.00e-01 9.40e-02 2.05e+00]
 [4.70e+02 5.00e-01 1.02e-01 2.28e+00]
 [4.70e+02 5.00e-01 9.50e-02 2.35e+00]
 [4.70e+02 4.00e-01 1.40e-01 2.29e+00]
 [4.70e+02 5.00e-01 9.10e-02 2.14e+00]
 [4.70e+02 5.00e-01 1.43e-01 2.25e+00]
 [4.70e+02 6.00e-01 9.70e-02 2.24e+00]
 [4.70e+02 4.00e-01 9.30e-02 2.08e+00]
 [4.70e+02 5.00e-01 1.08e-01 2.35e+00]
 [4.70e+02 5.00e-01 9.00e-02 2.40e+00]
 [4.70e+02 5.00e-01 1.00e-01 2.32e+00]
 [4.70e+02 5.00e-01 1.21e-01 2.38e+00]
 [4.70e+02 6.00e-01 1.13e-01 2.30e+00]
 [4.70e+02 6.00e-01 8.20e-02 2.36e+00]
 [4.70e+02 4.00e-01 1.06e-01 2.10e+00]
 [4.70e+02 5.00e-01 1.25e-01 2.09e+00]
 [4.70e+02 6.00e-01 1.39e-01 2.22e+00]
 [4.70e+02 4.00e-01 1.19e-01 2.18e+00]
 [4.70e+02 5.00e-01 1.26e-01 2.30e+00]
 [4.70e+02 5.00e-01 1.03e-01 2.37e+00]
 [4.70e+02 4.00e-01 1.36e-01 2.13e+00]
 [4.70e+02 5.00e-01 1.08e-01 2.31e+00]
 [4.70e+02 6.00e-01 9.20e-02 2.21e+00]
 [4.70e+02 5.00e-01 9.80e

In [4]:
print(Y)

[10.89 10.24  9.68 23.38  4.66 13.73 18.58  3.62 11.67 26.39 19.35 18.78
 16.87 23.29 24.46 23.6  23.24  5.64 13.79 24.02  5.66 23.3   3.26 12.36
 13.72  2.9   3.81 16.68 11.3  15.01 26.35 26.88  4.91 17.75 13.94 15.72
 17.47  2.23  3.99 25.69 19.81 14.84 19.31 20.06  6.14 26.22  3.17 15.62
 14.22 18.22 24.14 10.58 25.44 27.29 17.76 10.6  10.87 15.42 20.67  2.83
  2.51  7.17 20.35  3.22  8.44  3.07  3.5   8.29  3.15  2.82  7.29  2.52
 14.08 16.38 11.3  17.02 23.12  2.94 24.72  9.36 20.43 10.65 22.4   8.76
  3.41  8.12 17.25  9.69 11.71 14.77  4.05  4.17 21.69 13.04 15.65 23.27
 19.54 23.45 26.08  2.9   8.05 11.3  26.58  6.16  6.06 18.26 12.93 20.91
 18.73 18.87  8.16  7.38 25.58 24.09  9.8  12.93 15.21  3.81  7.16  3.19
  5.75 20.99 20.19 27.36 16.06  8.77  3.32  4.67 17.74  7.01 26.45 27.05
  8.59 25.15 11.18 10.86  9.28 15.68 16.85  2.83  7.68 13.27  8.55  5.25
  6.12 26.13 16.46 17.5  27.32  8.35  4.07 17.71 15.83 12.31 11.82 20.84
 13.71 13.25 26.8  17.27 22.89 23.35 12.25 23.07 27

##Splitting the Dataset

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)



In [6]:
print(X_train)

[[4.70e+02 5.00e-01 9.70e-02 2.10e+00]
 [4.70e+02 4.00e-01 8.50e-02 2.16e+00]
 [4.70e+02 5.00e-01 1.44e-01 2.32e+00]
 [4.70e+02 4.00e-01 1.19e-01 2.18e+00]
 [4.70e+02 4.00e-01 9.20e-02 2.26e+00]
 [4.70e+02 6.00e-01 1.42e-01 2.21e+00]
 [4.70e+02 5.00e-01 1.12e-01 2.12e+00]
 [4.70e+02 4.00e-01 9.60e-02 2.27e+00]
 [4.70e+02 5.00e-01 1.32e-01 2.05e+00]
 [4.70e+02 5.00e-01 1.04e-01 2.24e+00]
 [4.70e+02 5.00e-01 1.13e-01 2.17e+00]
 [4.70e+02 6.00e-01 1.13e-01 2.11e+00]
 [4.70e+02 6.00e-01 8.30e-02 2.22e+00]
 [4.70e+02 5.00e-01 8.40e-02 2.39e+00]
 [4.70e+02 4.00e-01 1.38e-01 2.38e+00]
 [4.70e+02 6.00e-01 1.37e-01 2.15e+00]
 [4.70e+02 4.00e-01 1.13e-01 2.26e+00]
 [4.70e+02 6.00e-01 1.13e-01 2.30e+00]
 [4.70e+02 5.00e-01 1.31e-01 2.25e+00]
 [4.70e+02 5.00e-01 8.80e-02 2.17e+00]
 [4.70e+02 5.00e-01 1.21e-01 2.27e+00]
 [4.70e+02 5.00e-01 1.30e-01 2.14e+00]
 [4.70e+02 5.00e-01 1.04e-01 2.32e+00]
 [4.70e+02 4.00e-01 1.00e-01 2.20e+00]
 [4.70e+02 5.00e-01 1.24e-01 2.11e+00]
 [4.70e+02 5.00e-01 1.05e

In [7]:
print(Y_train)

[27.05 19.54 22.88 24.02 12.31 21.69 17.76 23.07 10.58 17.25  2.83  4.05
 15.68 11.3   6.12 14.77 18.87 24.46 16.68 13.27 11.54  3.17 16.85 20.75
 18.73 20.35  9.68  2.83  9.28  9.84 20.06 19.35 26.13 16.38  6.24 11.77
 20.15  3.32 13.04 25.58 26.8  18.22 24.14 10.89 15.65  8.16 23.27  8.44
 20.37 14.84  2.82 18.22 14.22  8.12 23.29 23.35 12.36 17.52 10.86  5.66
 23.6  24.72  6.06 25.44  8.05 23.12 23.38 15.21 27.56  4.01 18.58  3.15
  3.41 20.99 20.84 24.88 13.71  4.17  5.7  18.78  3.19 26.58 15.72 15.42
  3.07 10.24  5.75 12.25 19.31 18.26  8.59 23.9   5.64  3.99 25.15 27.29
 13.25 17.74 13.94 11.3   9.8  17.71 26.88 16.72  4.67 19.53  4.91  8.55
 20.02 17.5  15.01  2.9  22.4   9.36 12.93 27.32 16.38 14.08  2.94  2.9
  8.44 10.65 14.1   6.83 17.99 25.69 20.67  7.68 11.71  7.29  9.69 17.47
 23.3  26.39  6.16  8.29 25.13  3.81 15.62 25.46]


In [8]:
print(X_test)

[[4.70e+02 6.00e-01 1.39e-01 2.22e+00]
 [4.70e+02 5.00e-01 1.08e-01 2.31e+00]
 [4.70e+02 5.00e-01 1.36e-01 2.14e+00]
 [4.70e+02 5.00e-01 9.90e-02 2.21e+00]
 [4.70e+02 5.00e-01 1.36e-01 2.08e+00]
 [4.70e+02 6.00e-01 1.34e-01 2.20e+00]
 [4.70e+02 4.00e-01 1.40e-01 2.29e+00]
 [4.70e+02 6.00e-01 1.40e-01 2.08e+00]
 [4.70e+02 5.00e-01 1.00e-01 2.32e+00]
 [4.70e+02 5.00e-01 1.05e-01 2.07e+00]
 [4.70e+02 4.00e-01 1.43e-01 2.29e+00]
 [4.70e+02 5.00e-01 1.42e-01 2.18e+00]
 [4.70e+02 6.00e-01 7.80e-02 2.07e+00]
 [4.70e+02 6.00e-01 1.36e-01 2.33e+00]
 [4.70e+02 5.00e-01 8.10e-02 2.22e+00]
 [4.70e+02 5.00e-01 1.43e-01 2.25e+00]
 [4.70e+02 5.00e-01 1.28e-01 2.34e+00]
 [4.70e+02 4.00e-01 1.42e-01 2.21e+00]
 [4.70e+02 5.00e-01 1.38e-01 2.21e+00]
 [4.70e+02 4.00e-01 1.06e-01 2.34e+00]
 [4.70e+02 5.00e-01 8.10e-02 2.37e+00]
 [4.70e+02 5.00e-01 9.60e-02 2.20e+00]
 [4.70e+02 5.00e-01 8.50e-02 2.21e+00]
 [4.70e+02 6.00e-01 1.23e-01 2.30e+00]
 [4.70e+02 5.00e-01 1.31e-01 2.08e+00]
 [4.70e+02 6.00e-01 1.42e

In [9]:
print(Y_test)

[13.79 25.61 20.91 26.08 16.96  3.61 13.73 16.46 16.87 15.83  7.17  8.77
 17.79 11.82 20.43  3.62 17.75 26.45  2.23 11.3   5.51 26.13 26.22 17.27
  2.51 27.36 16.57 23.38 20.19  6.14 23.24 10.6   4.07  7.38  3.26  4.22
  7.01  4.66  8.76 12.93 11.18  3.5   3.81 24.09 13.    3.22 11.67 17.02
  7.16  5.25  2.52 16.06  5.79 23.45  8.35 13.72 26.35 22.89 19.81 10.87]


## Training the Multiple Linear Regression model on the Training set

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

##Predicting the Test set Results

In [11]:
Y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[13.56 13.79]
 [15.39 25.61]
 [13.99 20.91]
 [15.03 26.08]
 [13.67 16.96]
 [13.55  3.61]
 [15.47 13.73]
 [12.82 16.46]
 [15.59 16.87]
 [14.2  15.83]
 [15.42  7.17]
 [14.08  8.77]
 [13.92 17.79]
 [14.19 11.82]
 [15.42 20.43]
 [14.43  3.62]
 [15.17 17.75]
 [15.02 26.45]
 [14.31  2.23]
 [16.36 11.3 ]
 [16.2   5.51]
 [15.04 26.13]
 [15.29 26.22]
 [14.27 17.27]
 [13.77  2.51]
 [14.29 27.36]
 [15.43 16.57]
 [14.65 23.38]
 [15.04 20.19]
 [16.49  6.14]
 [15.12 23.24]
 [15.73 10.6 ]
 [16.89  4.07]
 [15.32  7.38]
 [14.72  3.26]
 [16.63  4.22]
 [15.51  7.01]
 [15.83  4.66]
 [15.8   8.76]
 [13.79 12.93]
 [14.76 11.18]
 [14.94  3.5 ]
 [14.83  3.81]
 [14.01 24.09]
 [14.8  13.  ]
 [13.82  3.22]
 [14.45 11.67]
 [14.86 17.02]
 [15.18  7.16]
 [15.02  5.25]
 [15.53  2.52]
 [16.28 16.06]
 [15.6   5.79]
 [14.17 23.45]
 [16.22  8.35]
 [14.38 13.72]
 [14.83 26.35]
 [13.55 22.89]
 [16.25 19.81]
 [15.43 10.87]]


##Evaluating the Model Performance

In [14]:
from sklearn.metrics import mean_squared_error, r2_score
print('MSE:',mean_squared_error(Y_test, Y_pred))
print('R2 score:',r2_score(Y_test, Y_pred))

MSE: 67.01651278694793
R2 score: -0.09352694666719374
