# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('DummyData.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[4.70e+02 6.00e-01 1.09e-01 2.25e+00]
 [4.70e+02 5.00e-01 1.39e-01 2.33e+00]
 [4.70e+02 6.00e-01 9.40e-02 2.05e+00]
 [4.70e+02 5.00e-01 1.02e-01 2.28e+00]
 [4.70e+02 5.00e-01 9.50e-02 2.35e+00]
 [4.70e+02 4.00e-01 1.40e-01 2.29e+00]
 [4.70e+02 5.00e-01 9.10e-02 2.14e+00]
 [4.70e+02 5.00e-01 1.43e-01 2.25e+00]
 [4.70e+02 6.00e-01 9.70e-02 2.24e+00]
 [4.70e+02 4.00e-01 9.30e-02 2.08e+00]
 [4.70e+02 5.00e-01 1.08e-01 2.35e+00]
 [4.70e+02 5.00e-01 9.00e-02 2.40e+00]
 [4.70e+02 5.00e-01 1.00e-01 2.32e+00]
 [4.70e+02 5.00e-01 1.21e-01 2.38e+00]
 [4.70e+02 6.00e-01 1.13e-01 2.30e+00]
 [4.70e+02 6.00e-01 8.20e-02 2.36e+00]
 [4.70e+02 4.00e-01 1.06e-01 2.10e+00]
 [4.70e+02 5.00e-01 1.25e-01 2.09e+00]
 [4.70e+02 6.00e-01 1.39e-01 2.22e+00]
 [4.70e+02 4.00e-01 1.19e-01 2.18e+00]
 [4.70e+02 5.00e-01 1.26e-01 2.30e+00]
 [4.70e+02 5.00e-01 1.03e-01 2.37e+00]
 [4.70e+02 4.00e-01 1.36e-01 2.13e+00]
 [4.70e+02 5.00e-01 1.08e-01 2.31e+00]
 [4.70e+02 6.00e-01 9.20e-02 2.21e+00]
 [4.70e+02 5.00e-01 9.80e

### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

### Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))

### Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


## Part 3 - Training the ANN

In [10]:
ann.compile(optimizer = 'adam', loss = 'mse', metrics = ['accuracy'])

### Compiling the ANN

### Training the ANN on the Training set

In [11]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
5/5 [==============================] - 1s 5ms/step - loss: 264.3780 - accuracy: 0.0000e+00
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 264.1459 - accuracy: 0.0000e+00
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 263.9217 - accuracy: 0.0000e+00
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 263.6942 - accuracy: 0.0000e+00
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 263.4600 - accuracy: 0.0000e+00
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 263.2342 - accuracy: 0.0000e+00
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 262.9927 - accuracy: 0.0000e+00
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 262.7632 - accuracy: 0.0000e+00
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 262.5182 - accuracy: 0.0000e+00
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 2

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [12]:
y_pred = ann.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

2/2 [==============================] - 0s 6ms/step
[[ 0.91620737 13.79      ]
 [ 0.88064927 25.61      ]
 [ 0.95593113 20.91      ]
 [ 0.87110358 26.08      ]
 [ 0.96635377 16.96      ]
 [ 0.91628814  3.61      ]
 [ 0.98914641 13.73      ]
 [ 0.96617925 16.46      ]
 [ 0.90264797 16.87      ]
 [ 0.93115503 15.83      ]
 [ 0.9900493   7.17      ]
 [ 0.96136308  8.77      ]
 [ 0.95629191 17.79      ]
 [ 0.82333475 11.82      ]
 [ 0.93235022 20.43      ]
 [ 0.94982308  3.62      ]
 [ 0.90821683 17.75      ]
 [ 0.98912472 26.45      ]
 [ 0.94570845  2.23      ]
 [ 0.97648579 11.3       ]
 [ 0.94992125  5.51      ]
 [ 0.87919927 26.13      ]
 [ 0.91786289 26.22      ]
 [ 0.79350716 17.27      ]
 [ 0.95954198  2.51      ]
 [ 0.81305599 27.36      ]
 [ 0.99066043 16.57      ]
 [ 0.9398241  23.38      ]
 [ 0.90651149 20.19      ]
 [ 0.96380335  6.14      ]
 [ 0.96183717 23.24      ]
 [ 0.93283761 10.6       ]
 [ 0.98291874  4.07      ]
 [ 0.96991432  7.38      ]
 [ 0.98574799  3.26      ]
 [ 0

### Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix:',cm)
print('Accuracy score:',accuracy_score(y_test, y_pred))

ValueError: continuous is not supported