# Support Vector Regression (SVR)

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('DummyData.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
y = y.reshape(len(y), 1)

##Splitting the Dataset

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
# Standardize the features
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train = scaler_X.fit_transform(X_train)
y_train = scaler_y.fit_transform(y_train)


In [ ]:
print(X_train)

[[ 0.   -0.1  -0.7  -1.2 ]
 [ 0.   -1.55 -1.33 -0.62]
 [ 0.   -0.1   1.75  0.93]
 [ 0.   -1.55  0.44 -0.42]
 [ 0.   -1.55 -0.96  0.35]
 [ 0.    1.34  1.65 -0.13]
 [ 0.   -0.1   0.08 -1.01]
 [ 0.   -1.55 -0.76  0.45]
 [ 0.   -0.1   1.12 -1.68]
 [ 0.   -0.1  -0.34  0.16]
 [ 0.   -0.1   0.13 -0.52]
 [ 0.    1.34  0.13 -1.1 ]
 [ 0.    1.34 -1.43 -0.04]
 [ 0.   -0.1  -1.38  1.61]
 [ 0.   -1.55  1.44  1.51]
 [ 0.    1.34  1.38 -0.71]
 [ 0.   -1.55  0.13  0.35]
 [ 0.    1.34  0.13  0.74]
 [ 0.   -0.1   1.07  0.25]
 [ 0.   -0.1  -1.17 -0.52]
 [ 0.   -0.1   0.55  0.45]
 [ 0.   -0.1   1.02 -0.81]
 [ 0.   -0.1  -0.34  0.93]
 [ 0.   -1.55 -0.55 -0.23]
 [ 0.   -0.1   0.71 -1.1 ]
 [ 0.   -0.1  -0.29 -1.49]
 [ 0.    1.34 -0.86 -1.68]
 [ 0.    1.34 -1.38 -0.81]
 [ 0.    1.34 -0.34 -0.13]
 [ 0.   -0.1   0.86 -0.62]
 [ 0.   -0.1  -1.54 -0.52]
 [ 0.   -0.1  -0.13  1.22]
 [ 0.    1.34 -0.02 -0.33]
 [ 0.    1.34 -1.85  1.71]
 [ 0.    1.34 -0.08  1.61]
 [ 0.   -0.1   1.49  1.13]
 [ 0.   -0.1   0.5   0.25]
 

In [ ]:
print(y_train)

[[ 1.64e+00]
 [ 6.32e-01]
 [ 1.08e+00]
 [ 1.23e+00]
 [-3.39e-01]
 [ 9.20e-01]
 [ 3.93e-01]
 [ 1.11e+00]
 [-5.72e-01]
 [ 3.24e-01]
 [-1.61e+00]
 [-1.45e+00]
 [ 1.13e-01]
 [-4.75e-01]
 [-1.17e+00]
 [-9.06e-03]
 [ 5.42e-01]
 [ 1.29e+00]
 [ 2.47e-01]
 [-2.11e-01]
 [-4.43e-01]
 [-1.57e+00]
 [ 2.70e-01]
 [ 7.94e-01]
 [ 5.23e-01]
 [ 7.40e-01]
 [-6.93e-01]
 [-1.61e+00]
 [-7.46e-01]
 [-6.71e-01]
 [ 7.01e-01]
 [ 6.06e-01]
 [ 1.52e+00]
 [ 2.07e-01]
 [-1.15e+00]
 [-4.12e-01]
 [ 7.13e-01]
 [-1.55e+00]
 [-2.41e-01]
 [ 1.44e+00]
 [ 1.61e+00]
 [ 4.54e-01]
 [ 1.25e+00]
 [-5.30e-01]
 [ 1.09e-01]
 [-8.97e-01]
 [ 1.13e+00]
 [-8.59e-01]
 [ 7.43e-01]
 [ 3.45e-04]
 [-1.61e+00]
 [ 4.54e-01]
 [-8.29e-02]
 [-9.02e-01]
 [ 1.14e+00]
 [ 1.14e+00]
 [-3.33e-01]
 [ 3.60e-01]
 [-5.34e-01]
 [-1.23e+00]
 [ 1.18e+00]
 [ 1.33e+00]
 [-1.18e+00]
 [ 1.42e+00]
 [-9.12e-01]
 [ 1.11e+00]
 [ 1.15e+00]
 [ 5.00e-02]
 [ 1.71e+00]
 [-1.45e+00]
 [ 5.03e-01]
 [-1.57e+00]
 [-1.53e+00]
 [ 8.26e-01]
 [ 8.06e-01]
 [ 1.35e+00]
 [-1.51e-01]

## Training the SVR model on the training dataset

In [ ]:
from sklearn.svm import SVR

# Creating and training the SVR model
regressor = SVR(kernel='rbf')
regressor.fit(X_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

##Predicting the Test set results

In [ ]:
y_pred = scaler_y.inverse_transform(regressor.predict(scaler_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[18.71 13.79]
 [15.37 25.61]
 [12.72 20.91]
 [17.1  26.08]
 [ 9.39 16.96]
 [16.65  3.61]
 [13.47 13.73]
 [10.93 16.46]
 [16.88 16.87]
 [16.03 15.83]
 [13.66  7.17]
 [15.32  8.77]
 [12.01 17.79]
 [20.21 11.82]
 [17.5  20.43]
 [16.34  3.62]
 [11.86 17.75]
 [19.65 26.45]
 [15.84  2.23]
 [ 9.02 11.3 ]
 [17.8   5.51]
 [17.33 26.13]
 [17.55 26.22]
 [17.26 17.27]
 [ 9.58  2.51]
 [19.71 27.36]
 [12.95 16.57]
 [15.04 23.38]
 [17.43 20.19]
 [10.99  6.14]
 [22.81 23.24]
 [17.85 10.6 ]
 [ 7.79  4.07]
 [22.7   7.38]
 [20.18  3.26]
 [ 6.85  4.22]
 [17.47  7.01]
 [17.72  4.66]
 [17.87  8.76]
 [ 9.23 12.93]
 [16.81 11.18]
 [12.67  3.5 ]
 [16.03  3.81]
 [17.23 24.09]
 [14.11 13.  ]
 [10.01  3.22]
 [11.82 11.67]
 [20.71 17.02]
 [18.45  7.16]
 [17.27  5.25]
 [18.2   2.52]
 [13.79 16.06]
 [17.79  5.79]
 [16.86 23.45]
 [ 6.11  8.35]
 [11.58 13.72]
 [16.05 26.35]
 [11.65 22.89]
 [14.28 19.81]
 [16.84 10.87]]


## Predictions of the results using Trained Dataset

In [ ]:
new_data = [[470, 0.5, 0.119, 2.32]]  # Values taken from the test set and the actual ouput was 5.7

# Standardize the new data using the previously fitted scaler
new_data_scaled = scaler_X.transform(new_data)

# Make predictions
new_pred_scaled = regressor.predict(new_data_scaled)

# Inverse transform the prediction to the original scale
new_pred = scaler_y.inverse_transform(new_pred_scaled.reshape(-1, 1)).flatten()

print(f'Predicted output: {new_pred}')


Predicted output: [13.21]


## Evaluating the model performance on the Testset

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))

Mean Squared Error: 67.57592025831386
R-squared: -0.10265495286546211
